/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gonzalezgarciadiego_ad03;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * <strong>Clase principal</strong><br>
 * Clase principal del proyecto, que llama desde el método main a las consultas
 * referentes a los puntos 1-5 de la tarea y crea el formulario para el punto
 * 6.<br>
 * Todos los métodos referentes al manejo de la base de datos, se desarrollan en
 * la clase BaseDatos.
 *
 * @author Diego González García
 */
public class AD03_BaseDeDatos extends javax.swing.JDialog {

    private static final BaseDatos baseDatos = new BaseDatos("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost:3306/Supermercado_r", "root", "");  //Creamos un objeto de base de datos
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    private String bdUsuario;
    private String bdCarrito;
    private String bdProducto;
    private String bdPVP;
    private String bdStock;
    private String bdCantidad;
    private String bdFecha;

    /**
     * <strong>Método constructor por defecto</strong><br>
     * Construye el formulario.
     *
     * @param parent
     * @param modal
     */
    public AD03_BaseDeDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * <strong>Método que inicializa los componentes del formulario.</strong><br>
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jLabelNCarrito = new javax.swing.JLabel();
        jLabelDescArticulo = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelPVP = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        mensajes = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        nCarrito = new javax.swing.JTextField();
        descArticulo = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        pvp = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de compras");
        setPreferredSize(new java.awt.Dimension(870, 320));
        setResizable(false);
        setSize(new java.awt.Dimension(870, 320));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelUsuario.setText("USUARIO");

        jLabelNCarrito.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelNCarrito.setText("Nº CARRITO");

        jLabelDescArticulo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelDescArticulo.setText("Desc. Articulo");

        jLabelContraseña.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelContraseña.setText("CONTRASEÑA");

        jLabelFecha.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelFecha.setText("FECHA");

        jLabelPVP.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelPVP.setText("PVP");

        jLabelCantidad.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        mensajes.setEditable(false);
        mensajes.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        usuario.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        nCarrito.setEditable(false);
        nCarrito.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        descArticulo.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        fecha.setEditable(false);
        fecha.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        pvp.setEditable(false);
        pvp.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        cantidad.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnComprar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensajes)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescArticulo)
                            .addComponent(jLabelNCarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario)
                            .addComponent(nCarrito)
                            .addComponent(descArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jLabelContraseña)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPVP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contraseña)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pvp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComprar)
                            .addComponent(btnLogin))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraseña)
                    .addComponent(jLabelUsuario)
                    .addComponent(btnLogin)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNCarrito)
                    .addComponent(nCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescArticulo)
                    .addComponent(descArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPVP)
                    .addComponent(jLabelCantidad)
                    .addComponent(pvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(btnComprar))
                .addGap(34, 34, 34)
                .addComponent(mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * <strong>Método que gestiona el funcionamiento del botón
     * "Consultar".</strong>
     *
     * @param evt
     */
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String aux; //Lee el método de la BD
        String[] parts; //Trocea el String de respuesta de la BD
        
        //Si no hay datos que consultar, termina el programa
        if(descArticulo.getText().isEmpty()){
            System.exit(0); //Termina el programa
        }
        
        aux = baseDatos.checkProducto(descArticulo.getText());    //Comprueba el artículo
        if (aux.isEmpty()) { //Si no hay datos muestra mensaje de error
            mensajes.setText("Artículo inexistente");
            bdProducto = "";    //Borra el producto anterior
            bdPVP = ""; //Borra la PVP anterior
            bdStock = "";   //Borra el Stock anterior
        } else {    //Si hay datos, el artículo existe y por tanto guardama su información
            mensajes.setText("");
            parts = aux.split("/");
            bdProducto = parts[0];  //Código del producto
            bdPVP = parts[1];   //PVP del producto
            bdStock = parts[2];   //Stock del producto
        }
        pvp.setText(bdPVP); //Muestra el precio del producto en el formulario
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * <strong>Método que gestiona el funcionamiento del botón
     * "Finalizar".</strong>
     *
     * @param evt
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.exit(0); //Termina el programa
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * <strong>Método que gestiona el funcionamiento del botón "Login".</strong>
     *
     * @param evt
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String aux; //Lee el método de la BD
        aux = baseDatos.checkUsuario(usuario.getText(), contraseña.getText());    //Comprueba el usuario y la contraseña
        
        //Si no hay datos de iniciar sesión
        if(usuario.getText().isEmpty() || contraseña.getText().isEmpty()){
            System.exit(0); //Termina el programa
        }
        
        if (aux.isEmpty()) { //Si no hay datos muestra mensaje de error
            mensajes.setText("El usuario y/o la contraseña son incorrectos");
            bdUsuario = ""; //Borra el usuario anterior
            bdFecha = "";   //Borra la fecha anterior
            bdCarrito = ""; //Borra el carrito carrito
        } else {    //Si hay datos, el uusuario y contraseña con correctos
            mensajes.setText("");
            bdUsuario = aux;    //Almacena el código de usuario
            bdFecha = dtf.format(LocalDateTime.now());  //Guarda la fecha actual en una variable
            bdCarrito = String.valueOf(Integer.parseInt(baseDatos.lastCarrito()) + 2); //Guarda el código del último carrito almacenado +2 en una variable
        }
        fecha.setText(bdFecha); //Muestra la fecha en el formulario
        nCarrito.setText(bdCarrito);    //Muestra el nº de carrito en el formulario
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * <strong>Método que gestiona el funcionamiento del botón
     * "Comprar".</strong>
     *
     * @param evt
     */
    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String aux;
        
        //Si no hay datos de compra
        if(cantidad.getText().isEmpty()){
            System.exit(0); //Termina el programa
        }
        
        bdCantidad = cantidad.getText();    //Almacena la cantidad solicitada del producto
        bdStock = baseDatos.checkStockProducto(bdProducto); //Actualizamos el stock disponible del producto por si hubiese cambiado
        if (Integer.parseInt(bdCantidad) > Integer.parseInt(bdStock)) {  //Si la cantidad solicitada es mayor al stock
            mensajes.setText("Cantidad excesiva, Stock disponible: " + bdStock);
        } else {    //Si hay suficiente stock
            mensajes.setText("");
            baseDatos.compra(bdCarrito, bdUsuario, bdFecha, bdProducto, bdStock, bdCantidad);
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * <strong>Método principal</strong>
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AD03_BaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AD03_BaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AD03_BaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AD03_BaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //El objeto baseDatos está creado en la clase
        baseDatos.testConnection(); //Comprobamos que en la conexión no existen errores
        baseDatos.createDataBase("Supermercado_r"); //Borramos y creamos la base de datos
        baseDatos.createTables();   //Creamos las tablas de la base de datos
        baseDatos.addValors();  //Añadimos los valores a las tablas de la base de datos
        baseDatos.consulta1();  //Ejercicio 1
        baseDatos.consulta2();  //Ejercicio 2
        baseDatos.consulta3();  //Ejercicio 3
        baseDatos.consulta4();  //Ejercicio 4
        baseDatos.consulta5();  //Ejercicio 5

        //Ejercicio 6
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AD03_BaseDeDatos dialog = new AD03_BaseDeDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField cantidad;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField descArticulo;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelDescArticulo;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNCarrito;
    private javax.swing.JLabel jLabelPVP;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField mensajes;
    private javax.swing.JTextField nCarrito;
    private javax.swing.JTextField pvp;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
