--T-SQL (Miscrosoft SQL Server)
select * into golesbkp from goles;

--PL/SQL
--DDL y DML (select-insert) 
create table golesbkp as select * from goles;

--DDL-
create table GOLESBKP as select * from GOLES where 1 = 2;

-- Sintaxis estandar
insert into [nombre_tabla] (columna1, columna2,.....) values(valor1, valor2,.....);
INSERT INTO GOLESBKP (numfila, jornada, numpartido,periodo, minuto, jugador, pp) VALUES(81,3,10,2,NULL,9,0)


-- Lista de columnas de ambas tablas sea igual
insert into gOLESbkp select * from GOLES;
-- Si la lista de columnas no es igual
insert into golesbkp (numfila,jornada, numpartido) select numfila, jornada,  numpartido from goles;


-- MEZCLA

--Actualiza a nulo la columna jugador en aquellos registros cuyo numfila sea par.
update goles set jugador=null where mod(numfila,2)=0
delete from goles where numpartido=8

select * from goles

select * from golesbkp

MERGE INTO goles gol USING golesbkp golbkp ON (gol.numfila=golbkp.numfila)
WHEN MATCHED THEN UPDATE SET gol.jugador = golbkp.jugador 
WHEN NOT MATCHED THEN INSERT (numfila, jornada, numpartido,periodo, minuto, jugador, pp) 
VALUES (golbkp.numfila, golbkp.jornada, golbkp.numpartido,golbkp.periodo, golbkp.minuto, golbkp.jugador, golbkp.pp);

--TRUNCATE/DELETE
--T-SQL
TRUNCATE--> AUTONUMÉRICOS-->Vuelven al valor inicial

--PL/SQL no vuelve los autonuméricos al valor inicial.

ALTER TABLE [TableName] MODIFY(ID GENERATED ALWAYS AS IDENTITY (START WITH 1));

create table usuario(
idusuario number generated always as identity primary key,
nombre vachar2(30) default ''
)

insert into usuario (nombre) values('Marisa');

create table usuario2(
idusuario number generated default as identity primary key
nombre vachar2(30) default ''
)
insert into usuario2 (nombre) values('Marisa');
insert into usuario2 (idusuario,nombre) values (3,'Marisa');

ALTER TABLE [TableName] MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE [TableName] MODIFY ID GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);