/*
 * Departamento
 *
 * Generated with Matisse Schema Definition Language 8.4.8
 * Generation date: Sun Nov 20 02:42:50 2011
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package doctoradomatisseoql;

import com.matisse.reflect.*;


/**
 * <code>Departamento</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Departamento extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 8.4.8
     * Generation Date: Sun Nov 20 02:42:50 2011
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Departamento</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("Departamento"));

    /**
     * Gets the <code>Departamento</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Departamento(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param clazz a class descriptor (the class to instantiate)
     */
    protected Departamento(com.matisse.reflect.MtClass clazz)  {
        super(clazz);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Departamento.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Departamento.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Departamento.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Departamento.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nombre' */

    /** Attribute <code>nombre</code> cache ID */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre",CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreCID);
    }


    /**
     * Gets the <code>nombre</code> attribute value.
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'formado_por' */

    /** Relationship <code>formado_por</code> cache ID */
    private static int formado_porCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("formado_por",CID));

    /**
     * Gets the <code>formado_por</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getFormado_porRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(formado_porCID);
    }

    /**
     * Gets the <code>formado_por</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getFormado_porSize
     * @see #formado_porIterator
     * @see #setFormado_por
     * @see #removeFormado_por
     */
    public final Profesor[] getFormado_por() {
        return (Profesor[])getSuccessors(getFormado_porRelationship(getMtDatabase()), Profesor.class);
    }

    /**
     * Counts the <code>formado_por</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getFormado_por
     * @see #formado_porIterator
     * @see #setFormado_por
     * @see #removeFormado_por
     */
    public final int getFormado_porSize() {
        return getSuccessorSize(getFormado_porRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>formado_por</code> relationship's successors.
     * @return an object iterator
     *
     * @see #getFormado_por
     * @see #getFormado_porSize
     * @see #setFormado_por
     * @see #removeFormado_por
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> formado_porIterator() {
        return this.<E>successorIterator(getFormado_porRelationship(getMtDatabase()), Profesor.class);
    }

    /**
     * Sets the <code>formado_por</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     * @see #removeFormado_por
     */
    public final void setFormado_por(Profesor[] succs) {
        setSuccessors(getFormado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>formado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     * @see #setFormado_por
     * @see #removeFormado_por
     */
    public final void prependFormado_por(Profesor succ) {
        prependSuccessor(getFormado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>formado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getFormado_por
     * @see #setFormado_por
     * @see #removeFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     */
    public final void appendFormado_por(Profesor succ) {
        appendSuccessor(getFormado_porRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>formado_por</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getFormado_por
     * @see #setFormado_por
     * @see #removeFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     */
    public final void appendFormado_por(Profesor[] succs) {
        addSuccessors(getFormado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>formado_por</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getFormado_por
     * @see #setFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     */
    public void removeFormado_por(Profesor[] succs) {
        removeSuccessors(getFormado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>formado_por</code> successors list.
     * @param succ the object to remove
     *
     * @see #getFormado_por
     * @see #setFormado_por
     * @see #getFormado_porSize
     * @see #formado_porIterator
     */
    public void removeFormado_por(Profesor succ) {
        removeSuccessor(getFormado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>formado_por</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearFormado_por() {
        clearSuccessors(getFormado_porRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Departamento(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Departamento]";
    }
}
