--------------------------------------------------------
-- Archivo creado  - sábado-enero-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "C##EJER3"."EQUIPOS" 
   (	"CODEQ" CHAR(3 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"LOCALIDAD" VARCHAR2(20 BYTE), 
	"ESTADIO" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"ESCUDO" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"FOTOPLANTILLA" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJER3.EQUIPOS
SET DEFINE OFF;
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('ALB','At. Albericia','Santander','Juan Hormaechea',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('BAR','S.D.  Barreda','Torrelavega','Barreda',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('BZN','C.D. Bezana','Santa Cruz de Bezana','Santa Cruz de Bezana',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('CAS','Castro F.C.','Castro Urdiales','Riomar',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('CAY','C.D. Cayon','Sarón','Fernando Astobiza',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('COL','C.D.  Colindres','Colindres','El Carmen',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('ESC','UM Escobedo','Camargo','Escobedo',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('GIM','Gimnastica de Torrelavega','Torrelavega','El Malecón',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('GNZ','C.D. Guarnizo','Guarnizo','Campos de El Pilar',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('LAR','C.D. Laredo','Laredo','Laredo1',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('MER','E.M.F. Meruelo','Meruelo','Meruelo',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('RAC','Racing B','Santander','El Sardinero',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('RAY','D. Rayo Cantabria','Santander','San Román de la Lanilla',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('REV','S.D. Revilla','Revilla de Camargo','Revilla',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('SEL','Selaya F.C','Selaya','Selaya',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('SIE','A.D. Siete Villas','Castillo','Castillo',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('TRO','C.D. Tropezon','Torrelavega','Santa Ana',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('TXE','S.D. Textil Escudo','Cabezon de la Sal','Juan Mª Pares',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('VEL','Velarde C.F.','Muriedas','La Maruca',null,null);
Insert into C##EJER3.EQUIPOS (CODEQ,NOMBRE,LOCALIDAD,ESTADIO,ESCUDO,FOTOPLANTILLA) values ('VIM','C.F. Vimenor','Vioño','Vioño',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008859
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."SYS_C008859" ON "C##EJER3"."EQUIPOS" ("CODEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008860
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."SYS_C008860" ON "C##EJER3"."EQUIPOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."EQUIPOS" MODIFY ("CODEQ" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."EQUIPOS" MODIFY ("LOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."EQUIPOS" ADD PRIMARY KEY ("CODEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJER3"."EQUIPOS" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  
  --------------------------------------------------------
-- Archivo creado  - sábado-enero-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PARTIDOS
--------------------------------------------------------

  CREATE TABLE "C##EJER3"."PARTIDOS" 
   (	"NUMJORNADA" NUMBER(4,0), 
	"NUMPARTIDO" NUMBER(4,0), 
	"EQLOC" CHAR(3 BYTE) DEFAULT NULL, 
	"EQVIS" CHAR(3 BYTE) DEFAULT NULL, 
	"GOLESLOC" NUMBER(4,0) DEFAULT NULL, 
	"GOLESVIS" NUMBER(4,0) DEFAULT NULL, 
	"FECHA" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJER3.PARTIDOS
SET DEFINE OFF;
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','1','GNZ','TRO','0','1',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','2','VIM','BAR','2','2',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','3','TXE','ESC','1','0',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','4','COL','VEL','1','1',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','5','MER','SIE','0','0',to_date('13/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','7','REV','CAS','1','1',to_date('13/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','8','CAY','RAY','0','0',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','9','GIM','ALB','2','1',to_date('13/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('1','10','SEL','RAC','1','5',to_date('14/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','1','TRO','SEL','1','0',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','2','BAR','GNZ','1','0',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','3','ESC','VIM','2','2',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','4','VEL','TXE','4','1',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','5','SIE','COL','2','0',to_date('20/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','6','LAR','MER','1','0',to_date('20/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','7','CAS','BZN','3','1',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','8','RAY','REV','1','1',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','9','ALB','CAY','0','4',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('2','10','RAC','GIM','0','1',to_date('21/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','1','TRO','BAR','3','1',to_date('27/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','2','GNZ','ESC','0','0',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','3','VIM','VEL','5','1',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','4','TXE','SIE','1','1',to_date('27/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','5','COL','LAR','0','1',to_date('27/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','6','MER','CAS','0','5',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','7','BZN','RAY','0','0',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','8','REV','ALB','1','2',to_date('27/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','9','CAY','RAC','0','0',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('3','10','SEL','GIM','3','1',to_date('28/05/21','DD/MM/RR'));
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','1','BAR','SEL',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','2','ESC','TRO',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','3','VEL','GNZ',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','4','SIE','VIM',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','5','LAR','TXE',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','6','CAS','COL',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','7','RAY','MER',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','8','ALB','BZN',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','9','RAC','REV',null,null,null);
Insert into C##EJER3.PARTIDOS (NUMJORNADA,NUMPARTIDO,EQLOC,EQVIS,GOLESLOC,GOLESVIS,FECHA) values ('4','10','GIM','CAY',null,null,null);
--------------------------------------------------------
--  DDL for Index PK_PARTIDOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."PK_PARTIDOS" ON "C##EJER3"."PARTIDOS" ("NUMJORNADA", "NUMPARTIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PARTIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."PARTIDOS" MODIFY ("NUMJORNADA" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."PARTIDOS" MODIFY ("NUMPARTIDO" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."PARTIDOS" ADD CONSTRAINT "PK_PARTIDOS" PRIMARY KEY ("NUMJORNADA", "NUMPARTIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."PARTIDOS" ADD CONSTRAINT "FK_LOCAL_EQUIPOS" FOREIGN KEY ("EQLOC")
	  REFERENCES "C##EJER3"."EQUIPOS" ("CODEQ") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##EJER3"."PARTIDOS" ADD CONSTRAINT "FK_VIST_EQUIPOS" FOREIGN KEY ("EQVIS")
	  REFERENCES "C##EJER3"."EQUIPOS" ("CODEQ") ON DELETE SET NULL ENABLE;
     
      
      
      --------------------------------------------------------
-- Archivo creado  - sábado-enero-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "C##EJER3"."JUGADORES" 
   (	"NUMJUG" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ALIAS" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"APELLIDOS" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"FECHANAC" DATE DEFAULT NULL, 
	"GOLES" NUMBER(11,0) DEFAULT 0, 
	"TARJ_AMARILLAS" NUMBER(11,0) DEFAULT 0, 
	"TARJ_ROJAS" NUMBER(11,0) DEFAULT 0, 
	"EQUIPO" CHAR(3 BYTE) DEFAULT NULL, 
	"PUESTO" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJER3.JUGADORES
SET DEFINE OFF;
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('1','Herrero','Pablo','Herrero  Fdz',to_date('21/03/87','DD/MM/RR'),'0','0','0','GIM','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('2','Chapi','Miguel','Calderón ',to_date('10/06/89','DD/MM/RR'),'0','0','0','GIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('3','Blanco','Mario ','Blanco Juarez',to_date('22/05/85','DD/MM/RR'),'0','0','0','GIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('4','Melli','Jorge','Herrero ',to_date('09/06/79','DD/MM/RR'),'0','0','0','GIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('5','Camus ','Borja','Camus de Miguel',to_date('28/10/82','DD/MM/RR'),'0','0','0','GIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('6','Kiko','Francisco','Garcia',to_date('17/08/96','DD/MM/RR'),'0','0','0','GIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('7','Fernandez','Victor','Fdz Gárate',to_date('12/07/92','DD/MM/RR'),'0','0','0','GIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('8','Siro','Siro','del Barrio Mdz',to_date('01/08/93','DD/MM/RR'),'0','0','0','GIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('9','Cano','Roberto','Cano',to_date('28/02/90','DD/MM/RR'),'0','0','0','GIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('10','Primo','Oscar','Conde Cruz',to_date('16/11/90','DD/MM/RR'),'0','0','0','GIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('11','Moreno','Marco','Moreno ',to_date('23/09/83','DD/MM/RR'),'0','0','0','GIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('12','Alonso','Kevin','Alonso Cosío',to_date('26/10/87','DD/MM/RR'),'0','0','0','GIM','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('13','Bustillo','Jaime','Bustillo',to_date('27/09/87','DD/MM/RR'),'0','0','0','GIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('14','Sepulveda','Maximiliano','Sepulveda',to_date('20/01/96','DD/MM/RR'),'0','0','0','GIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('15','Viti','Hugo','Vitienes Toyos',to_date('26/11/95','DD/MM/RR'),'0','0','0','GIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('16','Peón','Adrian','Peón García',to_date('09/03/91','DD/MM/RR'),'0','0','0','RAC','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('17','Rasines','Alex','Rasines Díez',to_date('16/01/89','DD/MM/RR'),'0','0','0','RAC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('18','Javi','Javi','Gomez Puebla',to_date('22/06/92','DD/MM/RR'),'0','0','0','RAC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('20','Chus','Jesús','Puras Esteban',to_date('16/10/97','DD/MM/RR'),'0','0','0','RAC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('21','Darío','Darío','Sánchez Somacarrera',to_date('30/07/82','DD/MM/RR'),'0','0','0','RAC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('23','Unai','Unai','Hernández Lestón',to_date('07/08/84','DD/MM/RR'),'0','0','0','RAC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('24','Prada','Álvaro','Prada Pontones',to_date('29/11/96','DD/MM/RR'),'0','0','0','RAC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('25','Mario','Mario','Martínez Mart',to_date('18/08/88','DD/MM/RR'),'0','0','0','CAY','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('26','Alex','Alejandro','Pérez Aja',to_date('19/03/94','DD/MM/RR'),'0','0','0','RAC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('27','Paulino','Paulino','Miguélez Fernández',to_date('08/01/84','DD/MM/RR'),'0','0','0','RAC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('28','Rubén Lavín','Rubén','Lavín Lavín',to_date('08/04/79','DD/MM/RR'),'0','0','0','CAY','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('29','Borja ','Borja ','Pelaez Cendon',to_date('30/01/86','DD/MM/RR'),'0','0','0','BAR','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('30','Gonzalo','Gonzalo','Ceballos Cosio',to_date('11/06/92','DD/MM/RR'),'0','0','0','BAR','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('31','Cristian','Cristan','Sainz Calderon',to_date('27/10/82','DD/MM/RR'),'0','0','0','BAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('32','Manuel ','Manuel','Diego Puente',to_date('25/07/99','DD/MM/RR'),'0','0','0','BAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('33','Aitor','Aitor','Santamaria Miguel',to_date('26/03/86','DD/MM/RR'),'0','0','0','BAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('34','Pedro','Pedro Jose','Rodrgez Blanco',to_date('06/04/95','DD/MM/RR'),'0','0','0','BAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('35','Christian','Christian','Gutierrez Villanueva',to_date('15/06/96','DD/MM/RR'),'0','0','0','BAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('36','Cristian','Cristian','Noval Lupion',to_date('29/04/96','DD/MM/RR'),'0','0','0','BAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('37','Adrian','Adrian','Llama Gutierrez',to_date('08/02/92','DD/MM/RR'),'0','0','0','BAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('38','Javier','Javier','Cabrero Calleja',to_date('13/05/92','DD/MM/RR'),'0','0','0','BAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('39','Ruben','Ruben','Ruiz Sainz',to_date('05/05/85','DD/MM/RR'),'0','0','0','BAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('40','Jesus','Jesus','Lombilla Ruiz',to_date('03/06/91','DD/MM/RR'),'0','0','0','BAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('41','Ruben','Ruben ','Estebanez Eguren',to_date('03/12/79','DD/MM/RR'),'0','0','0','BAR','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('42','Alvaro','Alvaro','Acebo Gonzalez',to_date('19/02/88','DD/MM/RR'),'0','0','0','BAR','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('43','Marcos','Marcos','Hoyas Balbas',to_date('06/10/79','DD/MM/RR'),'0','0','0','BAR','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('44','Álex Bolado','Alejandro','Bolado Díaz',to_date('14/03/97','DD/MM/RR'),'0','0','0','CAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('45','Delgado','Manuel','Delgado',to_date('01/08/83','DD/MM/RR'),'0','0','0','RAC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('46','Rubi','Rubén','Fernández Agudo',to_date('05/02/89','DD/MM/RR'),'0','0','0','CAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('47','Juanjo','Juan José','Herrero Ortiz',to_date('02/08/94','DD/MM/RR'),'0','0','0','CAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('48','Badiola','Víctor','Badiola Jiménez',to_date('23/06/84','DD/MM/RR'),'0','0','0','RAC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('49','Richi','Franck','Richi Kuita',to_date('09/06/80','DD/MM/RR'),'0','0','0','RAC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('50','Víctor','Víctor','Fernández Maza',to_date('26/07/90','DD/MM/RR'),'0','0','0','CAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('51','Somavilla','Jorge','Somavilla Bolado',to_date('12/05/90','DD/MM/RR'),'0','0','0','RAC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('52','Javi','Javier','Delgado Quintana',to_date('10/12/79','DD/MM/RR'),'0','0','0','CAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('53','Peramato','Jorge','Peramato Herrero',to_date('01/06/91','DD/MM/RR'),'0','0','0','SIE','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('54','Edu Río','Eduardo','Río Martínez',to_date('03/02/96','DD/MM/RR'),'0','0','0','CAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('55','Marcos','Marcos','Sáez Humara',to_date('24/01/85','DD/MM/RR'),'0','0','0','CAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('56','Álvaro','Álvaro','Ruiz San Román',to_date('04/11/99','DD/MM/RR'),'0','0','0','SIE','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('57','Rubén','Rubén','Bustillo Cavia',to_date('22/11/80','DD/MM/RR'),'0','0','0','VEL','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('58','Rubén','Rubén','Ruiz Lombera',to_date('20/09/88','DD/MM/RR'),'0','0','0','VEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('59','Javi','Javier','Muñoz Gómez',to_date('07/10/79','DD/MM/RR'),'0','0','0','VEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('60','Pablo','Pablo ','Ruiz Callirgos',to_date('15/06/95','DD/MM/RR'),'0','0','0','VEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('61','Kike','José Enrique','Arias del Rio',to_date('01/11/95','DD/MM/RR'),'0','0','0','VEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('62','Salas','David','Salas Gómez',to_date('22/08/92','DD/MM/RR'),'0','0','0','VEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('63','Oscar','Oscar','Merino de la Cruz',to_date('11/07/96','DD/MM/RR'),'0','0','0','VEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('64','Miguelín','Miguel','Delgado Gascon',to_date('24/07/83','DD/MM/RR'),'0','0','0','VEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('65','Jorge','Jorge ','Gomez Segurola',to_date('05/01/91','DD/MM/RR'),'0','0','0','VEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('66','Alberto','Alberto','Diez Ibarbia',to_date('23/03/83','DD/MM/RR'),'0','0','0','VEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('67','Diego','Diego','Gutiérrez Antolín',to_date('19/11/84','DD/MM/RR'),'0','0','0','VEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('68','Pellón','Jaime','Pellón Montes',to_date('28/07/95','DD/MM/RR'),'0','0','0','VEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('69','Temiño','Diego','Temiño Martínez',to_date('23/01/81','DD/MM/RR'),'0','0','0','VEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('70','Cagigas','Carlos','Cagigas Ballesteros',to_date('24/05/81','DD/MM/RR'),'0','0','0','CAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('71','Chema','José María','Torrontegui Fernández',to_date('07/08/84','DD/MM/RR'),'0','0','0','CAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('72','Diego','Diego','Fernández Sáiz',to_date('21/08/99','DD/MM/RR'),'0','0','0','CAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('73','Chus','Jesús','Laredo Abascal',to_date('07/04/81','DD/MM/RR'),'0','0','0','CAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('74','Cadaya','José Manuel','Cadaya Barba',to_date('12/03/91','DD/MM/RR'),'0','0','0','SIE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('75','Iker','Iker','Pazos Arranz',to_date('06/01/91','DD/MM/RR'),'0','0','0','SIE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('76','Colina','Iván','Colina López',to_date('28/04/81','DD/MM/RR'),'0','0','0','SIE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('77','Vicen','Vicente','Valle Pacheco',to_date('15/05/96','DD/MM/RR'),'0','0','0','SIE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('78','German','German','Álvarez Aspiazu',to_date('27/09/95','DD/MM/RR'),'0','0','0','SIE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('79','Javi','Javier','Angulo Candelera',to_date('01/06/89','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('80','Gandarillas','Mario','Gandarillas Cañizo',to_date('09/09/80','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('81','Rocha','Alberto','Toca Ugarte',to_date('26/12/97','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('82','Carlos','Carlos Juan','Liaño Nodar',to_date('28/09/84','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('83','Rubén','Rubén','Salamanca Antolín',to_date('17/07/92','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('84','Joel','Joel ','Canales Cea',to_date('02/05/87','DD/MM/RR'),'0','0','0','GNZ','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('85','Modino','Héctor ','Modino Martínez',to_date('10/11/79','DD/MM/RR'),'0','0','0','GNZ','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('86','Javi Martín','Javier ','Martín Expósito',to_date('29/01/00','DD/MM/RR'),'0','0','0','GNZ','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('87','Rafa','Rafael ','Escobedo Vargas',to_date('12/09/97','DD/MM/RR'),'0','0','0','GNZ','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('88','Dani','Daniel','Mediavilla Fernández',to_date('31/01/88','DD/MM/RR'),'0','0','0','GNZ','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('89','Richard','Ricardo ','García Rebollar',to_date('15/02/89','DD/MM/RR'),'0','0','0','GNZ','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('90','Chicha','Alejandro','Sáiz Traspuesto',to_date('20/03/81','DD/MM/RR'),'0','0','0','GNZ','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('91','Carlos','Carlos','Gutiérrez Sámanes',to_date('04/07/80','DD/MM/RR'),'0','0','0','GNZ','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('92','Leguina','Juan','Leguina González',to_date('18/09/79','DD/MM/RR'),'0','0','0','GNZ','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('93','Corral','Álvaro','Corral Gutiérrez',to_date('04/11/98','DD/MM/RR'),'0','0','0','GNZ','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('94','Sañudo','Manuel','Sañudo Olmo',to_date('15/12/91','DD/MM/RR'),'0','0','0','GNZ','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('95','Nico','Nicolás','González Fernández',to_date('23/01/84','DD/MM/RR'),'0','0','0','GNZ','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('96','Ibrahim','Ibrahim','Ruiz Rey',to_date('01/04/86','DD/MM/RR'),'0','0','0','GNZ','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('97','Alberto','Alberto ','Rivero Aguirre',to_date('15/11/99','DD/MM/RR'),'0','0','0','TXE','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('98','Adrian Diaz','Adrian ','Diaz Saiz',to_date('25/06/98','DD/MM/RR'),'0','0','0','TXE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('99','Pablo','Pablo','Iglesias Exposito',to_date('17/08/92','DD/MM/RR'),'0','0','0','TXE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('100','Dosal','Diego','Dosal Rivero',to_date('04/07/88','DD/MM/RR'),'0','0','0','TXE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('101','Pichu','Christian','Garcia Ruiz',to_date('24/06/85','DD/MM/RR'),'0','0','0','TXE','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('102','Bertuco','Alberto ','Mazon Bardon',to_date('09/09/82','DD/MM/RR'),'0','0','0','TXE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('103','Valdés','Diego','Valdés Acebo',to_date('24/10/98','DD/MM/RR'),'0','0','0','SIE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('104','Alex','Alejandro','Belíjar Arroyo',to_date('15/11/82','DD/MM/RR'),'0','0','0','CAS','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('105','Álvaro','Álvaro','Múgica Lastra',to_date('17/09/80','DD/MM/RR'),'0','0','0','CAS','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('106','Salva','Salvador','Hoya Alonso',to_date('30/09/96','DD/MM/RR'),'0','0','0','CAS','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('107','Andoni','Andoni','Llave Romaña',to_date('20/06/99','DD/MM/RR'),'0','0','0','CAS','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('108','Borja/Justo','Borja','Justo González',to_date('10/12/85','DD/MM/RR'),'0','0','0','CAS','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('109','Galder','Galder','Lecue Aspiazu',to_date('07/02/94','DD/MM/RR'),'0','0','0','CAS','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('110','Sepi','Joseba','Zorrilla Santiago',to_date('13/07/91','DD/MM/RR'),'0','0','0','CAS','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('111','Llamosa','Alejandro','Llamosas Castillo',to_date('29/02/96','DD/MM/RR'),'0','0','0','CAS','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('112','Juancar','Juan Carlos','Sánchez Valverde',to_date('27/01/85','DD/MM/RR'),'0','0','0','CAS','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('113','Gorka','Gorka','Cueto Muñoz',to_date('03/09/99','DD/MM/RR'),'0','0','0','CAS','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('114','Richi','Ricardo','Cantero Quintanilla',to_date('07/01/80','DD/MM/RR'),'0','0','0','CAS','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('115','Iván Argos','Iván','Argos Ocerín',to_date('05/11/84','DD/MM/RR'),'0','0','0','SIE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('116','Sabo','Ivan','Fernandez Muñoz',to_date('04/01/84','DD/MM/RR'),'0','0','0','COL','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('117','Álvaro','Álvaro Santamaría','Santamaría García',to_date('29/04/86','DD/MM/RR'),'0','0','0','SIE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('118','Manu Cobo','Manuel','Cobo Valle',to_date('09/06/79','DD/MM/RR'),'0','0','0','SIE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('119','Rubén Cobo','Rubén','Cobo Valle',to_date('04/01/80','DD/MM/RR'),'0','0','0','SIE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('120','Izan ','Izan','Hoyuela Iglesias',to_date('24/07/82','DD/MM/RR'),'0','0','0','TXE','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('121','Edgar','Edgar ','Diaz Bolado',to_date('05/08/93','DD/MM/RR'),'0','0','0','TXE','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('122','Cano','Pablo Antonio','Cano Gonzalez',to_date('19/02/99','DD/MM/RR'),'0','0','0','TXE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('123','Perujo','Daniel ','Fernandez Gutierrez',to_date('27/09/93','DD/MM/RR'),'0','0','0','TXE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('124','Raul Rivero','Raul ','Rivero Mier',to_date('12/02/92','DD/MM/RR'),'0','0','0','TXE','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('125','Ivan','Ivan','Gonzalez Fernandez',to_date('13/03/79','DD/MM/RR'),'0','0','0','TRO','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('126','Bustillo','Jaime','Bustillo Gil',to_date('03/06/82','DD/MM/RR'),'0','0','0','TRO','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('127','Estrada','Carlos','Estrada Villar',to_date('03/05/95','DD/MM/RR'),'0','0','0','TRO','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('128','Puente','Pablo','Puente Diaz',to_date('12/04/87','DD/MM/RR'),'0','0','0','TRO','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('129','Setien','Raul','Setien Chamorro',to_date('09/03/92','DD/MM/RR'),'0','0','0','TRO','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('130','Victor Sanchez','Victor','Sanchez Diaz',to_date('09/12/98','DD/MM/RR'),'0','0','0','TRO','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('131','Sergio Conde','Sergio','Conde Quintana',to_date('23/12/96','DD/MM/RR'),'0','0','0','TRO','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('132','Jose Luis','Jose Luis','Lavin Ruiz',to_date('26/11/87','DD/MM/RR'),'0','0','0','TRO','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('133','Dorronsoro','Alberto ','Dorronsoro Gonzalez',to_date('22/05/90','DD/MM/RR'),'0','0','0','TRO','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('134','Ricki','Ricardo','Fernandez Revuelta',to_date('25/01/88','DD/MM/RR'),'0','0','0','TRO','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('135','Jaime Isuardi','Jaime','Isuardi Fernandez',to_date('25/12/89','DD/MM/RR'),'0','0','0','TRO','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('137','Cagigas','Luis','Cagigas Maza',to_date('10/08/99','DD/MM/RR'),'0','0','0','COL','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('138','Nacho','Nacho','Echevarria Rodriguez',to_date('01/04/99','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('139','Ivan','Ivan','Herboso Ranero',to_date('01/04/97','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('140','Borja','Borja','Santisteban Montejo',to_date('02/05/88','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('141','Adrian','Adrian','Tejido Alonso',to_date('23/09/91','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('142','Humada','Ivan','Humada Corro',to_date('21/06/93','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('143','Veci','Cesar','Veci Martinez',to_date('02/01/92','DD/MM/RR'),'0','0','0','COL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('144','Fonso Cano','Alfonso','Cano Santisteban',to_date('10/06/79','DD/MM/RR'),'0','0','0','COL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('145','Cholo','Sergio','Cano Santisteban',to_date('26/12/83','DD/MM/RR'),'0','0','0','COL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('146','Chuky','Jose Luis','Ochoa Trueba',to_date('05/06/81','DD/MM/RR'),'0','0','0','COL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('147','Jaime','Jaime','Mogro del Rio',to_date('27/12/96','DD/MM/RR'),'0','0','0','COL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('148','Faisu','Jonathan','Ortube Hubete',to_date('12/07/98','DD/MM/RR'),'0','0','0','ALB','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('149','Johny','Jonathan','González Beraza',to_date('10/07/80','DD/MM/RR'),'0','0','0','ALB','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('150','Peña','Carlos Manuel','Peña Díaz',to_date('23/10/90','DD/MM/RR'),'0','0','0','ALB','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('151','Pove','Adrián','Povedano Ortigueira',to_date('27/04/91','DD/MM/RR'),'0','0','0','ALB','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('152','Julian','Julián','Moreno Avendaño',to_date('03/01/84','DD/MM/RR'),'0','0','0','ALB','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('153','Manu','Manuel',' Marquez Monterdez',to_date('16/11/87','DD/MM/RR'),'0','0','0','ESC','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('154','Richy','Ricardo ','Muela Oria',to_date('13/03/87','DD/MM/RR'),'0','0','0','ESC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('155','Nando','Fernando','Fuentevilla Landeras',to_date('02/03/93','DD/MM/RR'),'0','0','0','ESC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('156','Pedrajo','Guillermo','Pedrajo Carral',to_date('07/02/83','DD/MM/RR'),'0','0','0','ESC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('157','German','German','Gutierrez Herrera',to_date('18/10/98','DD/MM/RR'),'0','0','0','ESC','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('158','Tato','Luis Alberto','Diaz Ocerin',to_date('20/07/81','DD/MM/RR'),'0','0','0','ESC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('159','Dosal','Alvaro','Dosal San Martin',to_date('20/02/95','DD/MM/RR'),'0','0','0','ESC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('160','Hector','Hector','Tirado Vega',to_date('24/11/88','DD/MM/RR'),'0','0','0','ESC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('161','Canales','Miguel','Canales Madrazo',to_date('26/11/79','DD/MM/RR'),'0','0','0','ESC','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('162','Espino','Jesús ',' Espino Rodríguez',to_date('11/08/95','DD/MM/RR'),'0','0','0','ESC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('163','Jorge Vélez','Jorge','Vélez González',to_date('13/03/96','DD/MM/RR'),'0','0','0','ESC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('164','Vitali','Vitali','Bilous',to_date('30/12/93','DD/MM/RR'),'0','0','0','ESC','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('165','Guillermo','Guillermo','Sanchez Gonzalo',to_date('22/03/81','DD/MM/RR'),'0','0','0','ALB','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('166','Lavín','Pablo','Lavín Quevedo',to_date('28/11/86','DD/MM/RR'),'0','0','0','ALB','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('167','Cúper','Hector','Gancedo Gutiérrez',to_date('16/09/90','DD/MM/RR'),'0','0','0','ALB','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('168','Pablín','Pablo Javier','Lantarón Díaz',to_date('27/08/92','DD/MM/RR'),'0','0','0','ALB','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('169','Adrián Torre','Adrián','Torre Ruiz',to_date('26/12/90','DD/MM/RR'),'0','0','0','ALB','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('170','Luismi','Luis Miguel','Camargo Martinez',to_date('10/10/97','DD/MM/RR'),'0','0','0','ALB','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('171','Marcelo','Marcelo','Mateo Alonso',to_date('06/10/94','DD/MM/RR'),'0','0','0','SEL','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('172','Jorge','Jorge','Fernandez Sainz',to_date('01/05/80','DD/MM/RR'),'0','0','0','SEL','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('173','Bruno','Bruno','Sainz Sainz',to_date('29/02/80','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('174','Barquin','Oscar','Barquin Gutierrez',to_date('20/08/80','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('175','Roman','Roman','Carral Lavin',to_date('04/07/83','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('176','Martin','Martin','Ruiz Fernandez',to_date('10/06/96','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('177','Moral','David','Moral Prat',to_date('20/07/89','DD/MM/RR'),'0','0','0','LAR','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('178','Cano','Roberto ','Cano Santisteban',to_date('01/04/79','DD/MM/RR'),'0','0','0','LAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('179','Garcia','Pablo Javier','Garcia de Celis',to_date('21/05/90','DD/MM/RR'),'0','0','0','LAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('180','Collado','Antonio','Cano Collado',to_date('08/01/93','DD/MM/RR'),'0','0','0','LAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('181','Bubu','Alfredo','MannzanoGutierrez',to_date('16/10/93','DD/MM/RR'),'0','0','0','LAR','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('182','Alarzon','Borja','Alarzon Gil',to_date('20/09/89','DD/MM/RR'),'0','0','0','LAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('183','Felipe','Felipe','Peredo  Lopez',to_date('18/01/88','DD/MM/RR'),'0','0','0','LAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('184','Luis','Luis ','Gomez Abascal',to_date('25/11/91','DD/MM/RR'),'0','0','0','LAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('185','Oscar','Oscar ','San emeterio lezcano',to_date('10/03/95','DD/MM/RR'),'0','0','0','LAR','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('186','Dani','Daniel','Alvarez Estrda',to_date('26/01/00','DD/MM/RR'),'0','0','0','LAR','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('187','Vinatea','David','Vinatea Castillo',to_date('18/08/93','DD/MM/RR'),'0','0','0','LAR','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('188','Miguelin','Miguel Angel','García Alonso',to_date('04/10/88','DD/MM/RR'),'0','0','0','VIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('189','Gallo','Carlos','Gallo Díaz',to_date('23/09/83','DD/MM/RR'),'0','0','0','VIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('190','Sordo','José Manuel','Sordo Pí',to_date('28/02/94','DD/MM/RR'),'0','0','0','BZN','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('191','Mario','Mario','Sáiz Terán',to_date('21/06/98','DD/MM/RR'),'0','0','0','BZN','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('192','Javi Conde','Javier','Conde Pazuelos',to_date('18/09/88','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('193','Julian','Jose Julian','Gomez Garcia',to_date('22/12/89','DD/MM/RR'),'0','0','0','SEL','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('194','Esteban','Esteban','San Roman Sancho',to_date('23/07/83','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('195','Luis','Luis','Mesones Revuelta',to_date('01/09/89','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('196','Pablo','Pablo','Herrero Fernandez',to_date('02/07/97','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('197','Tomas','Tomas','Diego Garcia',to_date('06/05/97','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('198','Adrian','Adrian','Cobo Arroyo',to_date('23/01/94','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('199','Jacobo','Jacobo','España Diego',to_date('02/02/99','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('200','Chus','Jesus','Gutierrez Sanchez',to_date('08/02/92','DD/MM/RR'),'0','0','0','SEL','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('201','Mario Salcines','Mario','Salcines Herrero',to_date('29/01/84','DD/MM/RR'),'0','0','0','SEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('202','Herrero','Miguel Angel','Herrero Gozalez',to_date('17/11/85','DD/MM/RR'),'0','0','0','SEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('203','Borja Alonso','Borja','Alonso Gutierrez',to_date('23/12/97','DD/MM/RR'),'0','0','0','SEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('204','Teo','Teodoro','Revuelta Carral',to_date('13/02/90','DD/MM/RR'),'0','0','0','SEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('205','Gede','Gedeon','Saenz Ferandez',to_date('19/06/98','DD/MM/RR'),'0','0','0','SEL','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('206','Jandro','Alejandro','Pontones Terán',to_date('31/10/79','DD/MM/RR'),'0','0','0','REV','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('207','Pablo','Pablo','de la Vega Arnáiz',to_date('16/07/87','DD/MM/RR'),'0','0','0','REV','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('208','David','David','Revuelta Agudo',to_date('13/01/98','DD/MM/RR'),'0','0','0','REV','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('209','Igor','Igor','Hoyos de la cruz',to_date('01/06/85','DD/MM/RR'),'0','0','0','REV','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('210','Laro','Laro','Martínez Roldán',to_date('10/10/95','DD/MM/RR'),'0','0','0','REV','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('211','Piney','José','Fernández Piney',to_date('24/06/80','DD/MM/RR'),'0','0','0','REV','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('212','Diego Alonso','Diego','Alonso Ruiz',to_date('06/11/98','DD/MM/RR'),'0','0','0','REV','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('213','Rubén','Rubén','Obregon',to_date('06/09/89','DD/MM/RR'),'0','0','0','REV','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('214','Rado','Francisco','Rado Llorente',to_date('02/09/93','DD/MM/RR'),'0','0','0','REV','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('215','Azevedo','Luis Fernando','Azevedo Ferreira',to_date('21/02/99','DD/MM/RR'),'0','0','0','REV','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('216','Novoa','Jorge','Novoa Becerril',to_date('16/07/93','DD/MM/RR'),'0','0','0','REV','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('217','Alex','Alejandro','Sobrado Santiago',to_date('06/02/91','DD/MM/RR'),'0','0','0','BZN','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('218','Ricky','Ricardo','Costales Álvarez',to_date('11/09/95','DD/MM/RR'),'0','0','0','BZN','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('219','Mario Ruiz','Mario','Ruiz Cano',to_date('10/01/84','DD/MM/RR'),'0','0','0','BZN','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('220','Fernández','Diego','Fernández Pola',to_date('31/10/95','DD/MM/RR'),'0','0','0','BZN','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('229','Prieto','Óscar','Rubio Prieto',to_date('10/05/80','DD/MM/RR'),'0','0','0','BZN','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('230','Fito','Adolfo','Peña Quintano',to_date('19/05/82','DD/MM/RR'),'0','0','0','BZN','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('231','Marcos García ','Marcos ','García Alcalde',to_date('27/08/91','DD/MM/RR'),'0','0','0','BZN','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('232','Barrio','Pablo Javier','López Barrio',to_date('19/12/89','DD/MM/RR'),'0','0','0','BZN','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('233','Pablo','Pablo','Gómez Fernández',to_date('10/09/95','DD/MM/RR'),'0','0','0','BZN','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('234','José','José Alberto','Paz Martínez',to_date('30/05/87','DD/MM/RR'),'0','0','0','MER','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('235','Juan','Juan','Martinez del río',to_date('10/10/91','DD/MM/RR'),'0','0','0','MER','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('236','Juancar','Juan Carlos','Madrazo Gonzalez',to_date('23/06/96','DD/MM/RR'),'0','0','0','MER','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('237','Alvaro','Alvaro','Rodriguez Alonso',to_date('29/11/85','DD/MM/RR'),'0','0','0','MER','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('238','Charlis','Carlos','Férnandez Seco',to_date('05/12/81','DD/MM/RR'),'0','0','0','MER','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('239','Trobo','Rubén','Quintana Trobo',to_date('18/09/93','DD/MM/RR'),'0','0','0','MER','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('240','Eder','Eder','Rey Prada',to_date('25/08/80','DD/MM/RR'),'0','0','0','MER','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('241','Fer','Fernando','Fernandez Mendoza',to_date('22/11/84','DD/MM/RR'),'0','0','0','MER','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('242','Balbás','José Manuel','Balbás Muriel',to_date('07/05/82','DD/MM/RR'),'0','0','0','MER','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('243','Rambo','David','Alonso Ortizz',to_date('13/11/98','DD/MM/RR'),'0','0','0','MER','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('244','Cagigal','Jesús Avelino','Cagigal Durán',to_date('01/03/84','DD/MM/RR'),'0','0','0','MER','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('245','Viadero','Diego','Viadero Lezcano',to_date('07/01/87','DD/MM/RR'),'0','0','0','MER','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('246','Tolas','Borja','Delgado Veci',to_date('03/06/82','DD/MM/RR'),'0','0','0','MER','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('247','Zamorrana','David','Abad Rodriguez',to_date('11/11/92','DD/MM/RR'),'0','0','0','MER','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('248','Juanmi','Juan Miguel','Canales Gutierrez',to_date('23/11/95','DD/MM/RR'),'0','0','0','MER','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('249','Tear','Jaan','Philip Tear',to_date('27/09/79','DD/MM/RR'),'0','0','0','RAY','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('250','Raul Marin','Raul','Marín Conde',to_date('10/10/94','DD/MM/RR'),'0','0','0','RAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('251','Denny Palege','Denny Filipe ','Palege Escorcio',to_date('11/07/92','DD/MM/RR'),'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('252','Chus Sosa','Jesús David','Sosa Sebastia',null,'0','0','0','RAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('253','Álvaro Rodríguez','Álvaro','Rodriguez Rivas',null,'0','0','0','RAY','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('254','Josito','José Alberto','Padilla Carmona',null,'0','0','0','RAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('255','Jerin','Jerin Marcolino','Ramos Santos',null,'0','0','0','RAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('257','Ibón','Ibón','García Arrizabalaga',null,'0','0','0','RAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('258','Vilarchao','Víctor Manuel','Vilarchao Urtiaga',null,'0','0','0','RAY','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('259','Andreu','Andreu','García Luque',null,'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('260','Barletta','Tomás','Alejandro Barletta',null,'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('261','Emile','Emile','WAita Monemou',null,'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('262','Richi','Ricardo','García Pérez',null,'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('263','Domi Berlanga','Domingo','Berlanga Ouggoutti',null,'0','0','0','RAY','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('264','Gonzalo','Gonzalo','Saez de Quintanilla Noin',null,'0','0','0','RAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('265','Miguel','Miguel','Cabrillo Arce',null,'0','0','0','RAY','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('266','Iván Cabrero','Iván','Cabrero Serrano',null,'0','0','0','VIM','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('267','Samuel','Samuel','Martín Serrano',null,'0','0','0','VIM','portero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('268','Bringas','Adrián','Bringas Crespo',null,'0','0','0','VIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('269','Chapi','Miguel','Calderón Huelga',null,'0','0','0','VIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('270','Cripi','Christian','Gómez León',null,'0','0','0','VIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('271','Sergio','Sergio','San Miguel Gómez',null,'0','0','0','VIM','defensa');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('272','Fran Nazabal','Francisco','Nazabal Fernández',null,'0','0','0','VIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('273','Mantilla','Rubén','Mantilla Saiz',null,'0','0','0','VIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('274','Sergio Cos','Sergio','de Cos Rico',null,'0','0','0','VIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('275','Héctor','Héctor','Calleja López',null,'0','0','0','VIM','centrocampista');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('276','Pereda','Javier','Pereda Bueno',null,'0','0','0','VIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('277','Villar','Diego','Villar Cayón',null,'0','0','0','VIM','delantero');
Insert into C##EJER3.JUGADORES (NUMJUG,ALIAS,NOMBRE,APELLIDOS,FECHANAC,GOLES,TARJ_AMARILLAS,TARJ_ROJAS,EQUIPO,PUESTO) values ('278','Robin','Robson','Alonso Alves',null,'0','0','0','VIM','delantero');
--------------------------------------------------------
--  DDL for Index SYS_C008897
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."SYS_C008897" ON "C##EJER3"."JUGADORES" ("NUMJUG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."JUGADORES" MODIFY ("NUMJUG" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."JUGADORES" MODIFY ("ALIAS" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."JUGADORES" ADD CONSTRAINT "CK_PUESTO" CHECK (puesto in ('portero','defensa','centrocampista','delantero')) ENABLE;
  ALTER TABLE "C##EJER3"."JUGADORES" ADD PRIMARY KEY ("NUMJUG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."JUGADORES" ADD CONSTRAINT "FK_JUGADOR_EQUIPO" FOREIGN KEY ("EQUIPO")
	  REFERENCES "C##EJER3"."EQUIPOS" ("CODEQ") ON DELETE SET NULL ENABLE;
      
      
      
      --------------------------------------------------------
-- Archivo creado  - sábado-enero-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASIFICACION
--------------------------------------------------------

  CREATE TABLE "C##EJER3"."CLASIFICACION" 
   (	"CODEQ" CHAR(3 BYTE), 
	"PJ" NUMBER(4,0) DEFAULT 0, 
	"PG" NUMBER(4,0) DEFAULT 0, 
	"PE" NUMBER(4,0) DEFAULT 0, 
	"GF" NUMBER(4,0) DEFAULT 0, 
	"GC" NUMBER(4,0) DEFAULT 0, 
	"PUNTOS" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJER3.CLASIFICACION
SET DEFINE OFF;
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('ALB','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('BAR','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('BZN','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('CAS','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('CAY','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('COL','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('ESC','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('GIM','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('GNZ','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('LAR','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('MER','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('RAC','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('RAY','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('REV','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('SEL','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('SIE','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('TRO','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('TXE','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('VEL','0','0','0','0','0','0');
Insert into C##EJER3.CLASIFICACION (CODEQ,PJ,PG,PE,GF,GC,PUNTOS) values ('VIM','0','0','0','0','0','0');
--------------------------------------------------------
--  DDL for Index SYS_C008862
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."SYS_C008862" ON "C##EJER3"."CLASIFICACION" ("CODEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLASIFICACION
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."CLASIFICACION" MODIFY ("CODEQ" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."CLASIFICACION" ADD PRIMARY KEY ("CODEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASIFICACION
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."CLASIFICACION" ADD CONSTRAINT "FK_CLAS_EQUIPOS" FOREIGN KEY ("CODEQ")
	  REFERENCES "C##EJER3"."EQUIPOS" ("CODEQ") ON DELETE SET NULL ENABLE;


--------------------------------------------------------
-- Archivo creado  - sábado-enero-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOLES
--------------------------------------------------------

  CREATE TABLE "C##EJER3"."GOLES" 
   (	"NUMFILA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"JORNADA" NUMBER(4,0), 
	"NUMPARTIDO" NUMBER(4,0), 
	"PERIODO" NUMBER(4,0) DEFAULT 1, 
	"MINUTO" NUMBER(4,0), 
	"JUGADOR" NUMBER, 
	"PP" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJER3.GOLES
SET DEFINE OFF;
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('1','2','4','1','5','67','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('2','2','4','1','10','122','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('3','2','4','1','32','67','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('4','2','4','1','36','67','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('5','2','4','2','61','68','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('6','2','2','1','22','41','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('7','1','4','2','15','145','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('8','1','4','2','38','68','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('10','1','3','2','93','123','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('12','1','2','2','78','188','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('13','1','2','1','18','189','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('18','1','2','1','31','40','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('19','1','2','2','78','39','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('20','2','5','2','6','118','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('21','2','5','2','15','119','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('22','1','9','2','16','12','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('23','1','9','2','22','15','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('24','1','9','2','26','13','1');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('25','2','7','1','24','191','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('26','2','7','2','48','105','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('27','2','7','2','59','110','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('28','2','7','2','89','114','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('29','1','1','1','44','133','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('30','2','6','1','17','180','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('31','1','10','1','7','204','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('32','1','7','1','23','216','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('33','2','8','1','14','209','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('34','2','1','1','29','130','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('35','3','1','1','39','133','1');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('36','3','1','2','17','133','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('37','3','1','2','21','133','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('38','3','1','2','44','130','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('39','1','7','1','10','114','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('40','1','10','1','21','27','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('41','1','10','1','44','27','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('42','1','10','2','22','23','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('43','1','10','2','27','49','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('44','1','10','2','37','48','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('45','2','3','1','44','189','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('46','2','3','2','11','276','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('47','2','3','2','39','163','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('48','2','3','2','44','163','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('49','2','7','1','24','191','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('50','2','8','1','38','264','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('51','2','9','1','27','50','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('52','2','9','1','30','73','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('53','2','9','2','22','73','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('54','2','9','2','35','71','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('55','2','10','1','39','14','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('56','3','3','1','16','64','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('57','3','3','2','2','276','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('58','3','3','2','6','189','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('59','3','3','2','15','276','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('60','3','3','2','35','274','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('61','3','3','2','44','277','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('62','3','4','2','21','115','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('63','3','4','2','25','123','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('64','3','5','1','24','187','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('65','3','6','1','4','113','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('66','3','6','1','16','108','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('67','3','6','1','17','106','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('68','3','6','1','20','112','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('69','3','6','1','41','112','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('70','3','10','1','22','192','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('71','3','10','1','31','3','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('72','3','10','2','1','10','0');
Insert into C##EJER3.GOLES (NUMFILA,JORNADA,NUMPARTIDO,PERIODO,MINUTO,JUGADOR,PP) values ('73','3','10','2','16','15','0');
--------------------------------------------------------
--  DDL for Index SYS_C008900
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJER3"."SYS_C008900" ON "C##EJER3"."GOLES" ("NUMFILA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GOLES
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."GOLES" MODIFY ("NUMFILA" NOT NULL ENABLE);
  ALTER TABLE "C##EJER3"."GOLES" ADD PRIMARY KEY ("NUMFILA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOLES
--------------------------------------------------------

  ALTER TABLE "C##EJER3"."GOLES" ADD CONSTRAINT "FK_GOLES_JUGADORES" FOREIGN KEY ("JUGADOR")
	  REFERENCES "C##EJER3"."JUGADORES" ("NUMJUG") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##EJER3"."GOLES" ADD CONSTRAINT "FK_GOLES_PARTIDOS" FOREIGN KEY ("JORNADA", "NUMPARTIDO")
	  REFERENCES "C##EJER3"."PARTIDOS" ("NUMJORNADA", "NUMPARTIDO") ON DELETE SET NULL ENABLE;

