/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di01_reservascoche;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        panelSeleccion = new javax.swing.JPanel();
        coche = new javax.swing.JButton();
        bicicleta = new javax.swing.JButton();
        furgoneta = new javax.swing.JButton();
        patinete = new javax.swing.JButton();
        separador2 = new javax.swing.JSeparator();
        salir = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuCoche = new javax.swing.JMenu();
        menuFurgoneta = new javax.swing.JMenu();
        menuBicicleta = new javax.swing.JMenu();
        menuPatinete = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de vehículos");
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Wide Latin", 0, 30)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Gestión de vehículos");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTitulo.setName(""); // NOI18N

        panelSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de vehículo eléctrico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        coche.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        coche.setText("Coche");
        coche.setToolTipText("Reservar coche eléctrico");
        coche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocheActionPerformed(evt);
            }
        });

        bicicleta.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        bicicleta.setText("Bicicleta");
        bicicleta.setToolTipText("Reservar bicicleta eléctrica");
        bicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicicletaActionPerformed(evt);
            }
        });

        furgoneta.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        furgoneta.setText("Furgoneta");
        furgoneta.setToolTipText("Reservar furgoneta eléctrica");
        furgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furgonetaActionPerformed(evt);
            }
        });

        patinete.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        patinete.setText("Patinete");
        patinete.setToolTipText("Reservar patinete eléctrico");
        patinete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patineteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(bicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patinete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(coche, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(furgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coche, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(furgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patinete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        salir.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        salir.setText("SALIR");
        salir.setToolTipText("Salir del programa");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        menuCoche.setText("Coche");
        menuCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCocheMouseClicked(evt);
            }
        });
        barraMenu.add(menuCoche);

        menuFurgoneta.setText("Furgoneta");
        menuFurgoneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFurgonetaMouseClicked(evt);
            }
        });
        barraMenu.add(menuFurgoneta);

        menuBicicleta.setText("Bicicleta");
        menuBicicleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBicicletaMouseClicked(evt);
            }
        });
        barraMenu.add(menuBicicleta);

        menuPatinete.setText("Patinete");
        menuPatinete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPatineteMouseClicked(evt);
            }
        });
        barraMenu.add(menuPatinete);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelSeleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(separador2)
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocheActionPerformed
        CocheElectrico cocheElectrico = new CocheElectrico (this, true);
        cocheElectrico.setVisible(true);
    }//GEN-LAST:event_cocheActionPerformed

    private void furgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furgonetaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_furgonetaActionPerformed

    private void bicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicicletaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_bicicletaActionPerformed

    private void patineteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patineteActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_patineteActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void menuCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCocheMouseClicked
        CocheElectrico cocheElectrico = new CocheElectrico (this, true);
        cocheElectrico.setVisible(true);
    }//GEN-LAST:event_menuCocheMouseClicked

    private void menuFurgonetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFurgonetaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_menuFurgonetaMouseClicked

    private void menuBicicletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBicicletaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_menuBicicletaMouseClicked

    private void menuPatineteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPatineteMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Lo sentimos, no tenemos disponible esta opción.", "", 2);
    }//GEN-LAST:event_menuPatineteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton bicicleta;
    private javax.swing.JButton coche;
    private javax.swing.JButton furgoneta;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuBicicleta;
    private javax.swing.JMenu menuCoche;
    private javax.swing.JMenu menuFurgoneta;
    private javax.swing.JMenu menuPatinete;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JButton patinete;
    private javax.swing.JButton salir;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    // End of variables declaration//GEN-END:variables
}
